title: Stefano Di Mauro
logo: /assets-img/Profilepic.png
description: Backend enthusiast, good knowledge of Python and SQL. Trying to improve and possibly find a position for Backend/DevOps.
show_downloads: true
theme: jekyll-theme-minimal
