title: My Portfolio
logo: /assets-img/profile-pic.jpg
#description: Backend enthusiast, good knowledge of Python and SQL, trying to improve and possibly find a position for Backend/DevOps.
show_downloads: false
theme: jekyll-theme-minimal
